version: 2

models:
  - name: bronze_haulage_trips
    columns:
      - name: trip_id
        tests:
          - not_null
      - name: equipment_id
        tests:
          - not_null
      - name: current_status
        tests:
          - not_null
          - accepted_values:
              values: ["LOADING", "HAULING", "DUMPING", "IDLE"]
      - name: material_type
        tests:
          - accepted_values:
              values: ["ORE", "WASTE"]
      - name: load_timestamp
      - name: dump_timestamp
      - name: is_deleted
      - name: source_file
      - name: ingested_at
      - name: event_timestamp
